#!/usr/bin/env bash
# Regenerates cloudflare-realip.conf from Cloudflare's official, live IP
# range list. Cloudflare's ranges change occasionally, so this is a script
# rather than a hardcoded file - run it once during setup and re-run
# periodically (e.g. a monthly cron job) to stay current.
#
# Usage: sudo ./update-cloudflare-ips.sh
# Writes: nginx_config/cloudflare-realip.conf (this script's own directory)
# Then:   sudo nginx -t && sudo systemctl reload nginx

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/cloudflare-realip.conf"

{
    echo "# Auto-generated by update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Restores the real visitor IP ($remote_addr) when requests arrive via"
    echo "# Cloudflare's proxy, using the CF-Connecting-IP header they set."
    echo "# Included from tamuevent.com.conf (see the commented-out include there)."
    echo

    for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
        curl -fsS "$url" | while read -r range; do
            [ -n "$range" ] && echo "set_real_ip_from $range;"
        done
    done

    echo
    echo "real_ip_header CF-Connecting-IP;"
} > "$OUT"

echo "Wrote $OUT"
